server:
  port: 9999
#指定redis信息 (如 host, ip, password)
spring:
  data:
    redis:
      host: 106.55.168.139
      port: 6379
      password: ifoxox


ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
  # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
  # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300
